### ISSUE TITLE
File-based implementation

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-object-storage#128]
### Feature description

There should be a file based implementation which can be used for testing and local development.

Running against real or Dockerised environment adds unnecessary overhead to the developer environment.

**Comment by sharpau** [comment]
I was looking for an alternative to [Apache JCloud](https://jclouds.apache.org/) for blob+local storage and was excited to see this project, but having local filesystem as an option is one of my requirements.
