### ISSUE TITLE
Let LocalStorageOperations be primary when present on classpath

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-object-storage#306]
### Feature description

`micronaut-object-storage-local` will typically be added as a test dependency, but then it will be two beans of type `ObjectStorageOperations<*, *, *>` in context, and this error will appear (when using micronaut-object-storage-gcp):
`Message: Multiple possible bean candidates found: [GoogleCloudStorageOperations, LocalStorageOperations]`

Even with this in application-test.yml:
```
micronaut:
  object-storage:
    gcp:
      default:
        enabled: false
    local:
      default:
        enabled: true
        bucket: some-bucket-name
```

This can be resolved with a factory that replaces the production instance with the LocalStorageOperations instance:

```
import io.micronaut.context.annotation.Factory
import io.micronaut.context.annotation.Replaces
import io.micronaut.objectstorage.ObjectStorageOperations
import io.micronaut.objectstorage.googlecloud.GoogleCloudStorageOperations
import io.micronaut.objectstorage.local.LocalStorageOperations
import jakarta.inject.Singleton

@Factory
class ObjectStorageOperationsFactory {

    @Singleton
    @Replaces(bean = GoogleCloudStorageOperations::class)
    fun buildObjectStorageOperations(localStorageOperations: LocalStorageOperations): ObjectStorageOperations<*, *, *> =
        localStorageOperations
}
```
I might have missed something in the docs or source, but I haven't found any other way to solve this so far.

I find the solution micronaut-cache is using quite nice. When adding test dependency to micronaut-cache-noop, the micronaut-cache-noop will automatically be primary.

**Comment by alvarosanchez** [comment]
This issue revealed the inability to toggle configuration, which has been tracked in #308
