### ISSUE TITLE
Could not resolve io.micronaut.objectstorage:micronaut-object-storage-aws:2.0.3

### ISSUE THREAD

**Issue by munishchouhan** [micronaut-projects/micronaut-object-storage#352]
### Expected Behavior

gradle should resolve io.micronaut.objectstorage:micronaut-object-storage-aws:2.0.3

### Actual Behaviour

Could not resolve io.micronaut.objectstorage:micronaut-object-storage-aws:2.0.3

### Steps To Reproduce

1. Micronaut web app with micronautVersion=3.10.1
2. I am following this documentation 
https://micronaut-projects.github.io/micronaut-object-storage/latest/guide/#introduction 

### Environment Information

- Mac Ventura
- openjdk version "17.0.8"

### Version

3.10.1

**Comment by munishchouhan** [comment]
same with 
Could not find io.micronaut.objectstorage:micronaut-object-storage-local

**Comment by alvarosanchez** [comment]
You definitely have something wrong in your build.

The dependency does exist: https://central.sonatype.com/artifact/io.micronaut.objectstorage/micronaut-object-storage-aws/2.0.3

Also, a new project generated from starter does not reproduce the issue:

```
curl --location --request GET 'https://prev.micronaut.io/create/default/com.example.demo?lang=JAVA&build=GRADLE&test=JUNIT&javaVersion=JDK_17&features=object-storage-aws' --output demo.zip
```
