### ISSUE TITLE
doc-examples tests are not executed

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-object-storage#93]
### Expected Behavior

Test are executed

### Actual Behaviour

Test are not executed. 

See: https://ge.micronaut.io/s/riyczvvhequvs/tests/overview

### Steps To Reproduce

clone `master` branch

```
 ./gradlew test --rerun-tasks                
```

### Version

3.6.1

**Comment by alvarosanchez** [comment]
They do run for me, also on CI. Have you tried with `--no-build-cache`?

Summoning @melix just in case he spots a mistake in the build

**Comment by melix** [comment]
This is independent of build cache or rerun tasks: it's a consequence of predictive test selection, which decided that since you have no changes to the sources, it's useless to run the tests. You can force it to run all tests by doing:

`PREDICTIVE_TEST_SELECTION=false ./gradlew test`

**Comment by alvarosanchez** [comment]
As far as I can tell, that was the case for tests in the `object-storage-*` projects, but `doc-examples:example-*` didn't show up at all.

That said, I believe it's a problem with Sergio's IDE not importing the project correctly

**Comment by sdelamo** [comment]
I don't think it is related with predictive test selection. As you can see in the scan, the build does not sees the `docs-examples` projects.

**Comment by sdelamo** [comment]
Please, note the build scan was generated executing it in the terminal.

**Comment by melix** [comment]
Oh I see, you're talking about the `doc-examples` project only, sorry I missed that. They are not included: https://ge.micronaut.io/s/riyczvvhequvs/projects

If I check locally they are: https://ge.micronaut.io/s/fvh47w5ckumz2

I'm quite confused :/

**Comment by sdelamo** [comment]
I removed my home directory `.gradle/caches` folder and it seems to be working now. sorry for the noise.
